// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo4knf0Zm09pUtwAK126fRQakdRvqaPG0',
    appId: '1:217199522378:web:f43e9bc1751f64c03f6cb3',
    messagingSenderId: '217199522378',
    projectId: 'mamas-recipe-c3e36',
    authDomain: 'mamas-recipe-c3e36.firebaseapp.com',
    storageBucket: 'mamas-recipe-c3e36.firebasestorage.app',
    measurementId: 'G-2SR4YVZP28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0F_q78k3U0JY0yZY99nGxMkKr16HsAQE',
    appId: '1:217199522378:android:5e5781e2beb9b1c63f6cb3',
    messagingSenderId: '217199522378',
    projectId: 'mamas-recipe-c3e36',
    storageBucket: 'mamas-recipe-c3e36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkRuBIPtHCUKF1i2IzJW9UpxJgJEsfG2w',
    appId: '1:217199522378:ios:1bb1b0b3435465f53f6cb3',
    messagingSenderId: '217199522378',
    projectId: 'mamas-recipe-c3e36',
    storageBucket: 'mamas-recipe-c3e36.firebasestorage.app',
    iosBundleId: 'com.example.mamaRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkRuBIPtHCUKF1i2IzJW9UpxJgJEsfG2w',
    appId: '1:217199522378:ios:1bb1b0b3435465f53f6cb3',
    messagingSenderId: '217199522378',
    projectId: 'mamas-recipe-c3e36',
    storageBucket: 'mamas-recipe-c3e36.firebasestorage.app',
    iosBundleId: 'com.example.mamaRecipe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDo4knf0Zm09pUtwAK126fRQakdRvqaPG0',
    appId: '1:217199522378:web:d09cf7730d20734c3f6cb3',
    messagingSenderId: '217199522378',
    projectId: 'mamas-recipe-c3e36',
    authDomain: 'mamas-recipe-c3e36.firebaseapp.com',
    storageBucket: 'mamas-recipe-c3e36.firebasestorage.app',
    measurementId: 'G-EVK308BRE7',
  );

}